### ISSUE TITLE
404 Error on Saving Settings 

### ISSUE THREAD

**Issue by ghost** [ssplugin/ss-entry-importer#1]
#### Description
Upon trying to save from each tab in the backend (buttons Continue, Upload etc), the plugin generates a 404 Error.

##### Scenario
- A custom admin url is implemented in the system however the plugin ignores this and assumes "admin" to be the admin url hence leading to the 404 exception.

##### Version
Craft : 3.4.16
Plugin: 1.0.1

**Comment by ssplugin** [comment]
@ghost

The new version of the plugin available now (1.0.2).
We have fixed cp URL issue. Now a custom admin URL is working.
