### ISSUE TITLE
Fix composer 2 compatibility

### ISSUE THREAD

**Issue by olivierbon** [ssplugin/ss-entry-importer#4]
There still seems to be an issue with composer 2 with `src/assetbundles/indexcpsection/IndexCPSectionAsset.php`.

Locally, I modified as below to get it to work:

<img width="467" alt="Craft_ aRwsJIfz@2x" src="https://user-images.githubusercontent.com/146041/120304031-afe56f80-c2cf-11eb-8c67-b15f7c1a1f92.png">

Class name + folder name change :)

**Comment by honsa** [comment]
Still an issue:

```
Class ssplugin\ssentryimporter\assetbundles\IndexCpSection\IndexCpSectionAsset 
located in ./vendor/ssplugin/ss-entry-importer/src/assetbundles/indexcpsection/IndexCPSectionAsset.php 
does not comply with psr-4 autoloading standard. Skipping.

Class ssplugin\ssentryimporter\assetbundles\SsEntryImporter\SsEntryImporterAsset 
located in ./vendor/ssplugin/ss-entry-importer/src/assetbundles/ssentryimporter/SsEntryImporterAsset.php 
does not comply with psr-4 autoloading standard. Skipping.
```
